stages:
  - test

image: docker:24.0.2

services:
  - docker:24.0.2-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHONPATH: "$CI_PROJECT_DIR"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - venv/

before_script:
  - apk add --no-cache python3 py3-pip py3-virtualenv docker-compose
  - docker pull postgres:16
  - python3 --version
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install -r server/requirements.txt
  - pip install pytest pytest-cov

server_tests:
  stage: test
  script:
    - source venv/bin/activate
    - pytest --cov=server --cov-report=term-missing server/tests/
    - docker-compose -f docker-compose.yml up -d
    - docker-compose exec db bash -c 'until pg_isready -U test_user; do sleep 1; done'
    - pytest --cov=server --cov-report=term-missing server/integration-tests
  after_script:
    - docker-compose -f docker-compose.yml down
  coverage: '/TOTAL\s+\d+\s+\d+\s+\d+\s+(\d+%)$/'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
