services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata: