version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"  # maps container port 5432 to host port 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: