services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
    networks:
      - my-net1

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - my-net1

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        VITE_SERVER_HOST_ADDRESS: ${VITE_SERVER_HOST_ADDRESS}
        VITE_STATUS_THRESHOLD: ${VITE_STATUS_THRESHOLD}
    ports:
      - "5173:80"
    networks:
      - my-net1

volumes:
  pgdata:

networks:
  my-net1:
    external: true